### ISSUE TITLE
🐛[BUG] KSNM - Operation Desert Storm

### ISSUE THREAD

**Issue by Squinkerdoodle** [HorizonFFXI/HorizonXI-Issues#104]
**What does this bug affect?**
Missing the occasional message after Wild Rage that states "The platoon scorpion does not have enough energy to attack!" and it stops attacking for about 10 to 30 seconds (based on capture), currently gives the same message they occasionally give after Earth Pounder that states "The platoon scorpion's legs are lodged in the rocks!"  and binds them. 

**Steps to Reproduce**
Go into the fight and feed the mobs TP until it uses Wild Rage while checking chat logs for the message / bind effect wearing off.

**Expected behavior**
Sometimes after a Wild Rage you see the message "The platoon scorpion does not have enough energy to attack!" and it stops attacking for about 10 - 30seconds.

**Setup Information**
Version 30220802_3

**Additional context**
Based on the capture wiki is incorrect in that when one uses a move the others mimic each time. It seems to be that when one uses a TP move it gives the other's ~1000ish TP and if that makes the other NMs reach 3000 tp they will do the same move along with the original NM. I came to the ~1000ish TP amount based on my testing. With godmode enabled (giving perfect dodge so there's no TP gained from them hitting me) I can give one NM 3000 TP repeatedly and the others would mimic it on the 3rd TP feeding.

Additionally currently the NMs may possibly have some sort of Regain trait giving them TP over time, though it may only take them up to 2999 TP only and not to the 3000 TP limit for them to use a move. I say this due to while testing, if I don't feed any of them TP for a minute or 2 and then give one 3000 tp the others will mimic the move the first time.

**Comment by dallano** [comment]
Going through some captures I also discovered that scorpions won't queue a mimic action if they're asleep. I also discovered that the scorpions have a delay to when they mimic the action. In fact: Almost all behavior report on wikipedia is utterly and entirely false..... We're going to get so many bug reports stating this KSNM isn't working properly.

Your theory of them having regain until 2999 TP appears to be false as the capture I saw, players kept the scorpions asleep for a little over 5-6 minutes, and after hitting the player a few times did not TP whatsoever.

Nice catch with the scorpions not attacking for like 30 seconds after using wild rage. I'll make sure to fix that. (Might make this KSNM infinitely easier lol)

You also seem to be correct that rather than mimicing 100% of the time, scorpions appear to gain 1000 TP. Only scorpions that have been gaining TP seem to mimic the ability.

**Comment by Squinkerdoodle** [comment]
> In fact: Almost all behavior report on wikipedia is utterly and entirely false..... 
True on so many pages it's laughable. I started just using it as a rough guide and watching/using the capture to base my testing on.

It was hard to tell what was really going on with the mimicking / tp sharing at face value without being able to see under the hood since it seemed it was more complicated than that.
