### ISSUE TITLE
🐛[BUG][Website] Missing AH history

### ISSUE THREAD

**Issue by PrinceOfParallax** [HorizonFFXI/HorizonXI-Issues#1129]
**What does this bug affect?**
Website AH history

**Steps to Reproduce**
Log in to the site

**Expected behavior**
Did the patch erase AH history on the website!? I am missing all sales from 2/2 until 2/20 and then some stuff since 2/21 and missing too

**Screenshots**
![image](https://user-images.githubusercontent.com/38820735/221300448-afbcd3dc-788b-421f-becb-c4481b0fd661.png)

**Setup Information**
Not sure I am just normal logged in

**Additional context**
Thank you

**Comment by ZellithS** [comment]
This may be relevant from Feb 24th maint notes.

"Backend work on the server to improve game performance. Due to this, you may only see the past 12 sale entries for all items on the auction house through the website."

https://discord.com/channels/933423693848260678/933752333668606002/1078773229369442395

**Comment by CriticalXI** [comment]
This is intended, we recently cleared out the auction house log to improve server performance and only kept the last 12 entries sold of each item.
