### ISSUE TITLE
🐛[BUG][Combat Igqira Weskit not properly applying Curse effect

### ISSUE THREAD

**Issue by mattryan2011** [HorizonFFXI/HorizonXI-Issues#1198]
**What does this bug affect?**

Igqira Weskit is not properly applying curse. causes mob to gain HP.

**Steps to Reproduce**

-equip Weskit (possibly any Igqira equipment)
-be melee'd until weskit applies curse effect

**Expected behavior**

Mob loses total HP but maintains current HP amount

**Screenshots**

**Setup Information**

**Additional context**

**Comment by CriticalXI** [comment]
Not likely a bug. The mob's total HP lowers which will look visible like they haven't lost any HP. The HP bar "shrinks" so to say in that if a mob was already at 60% and then cursed it would show something like 75% HP but this is because their total amount of HP has lowered. If you have further proof this isn't working correctly, feel free to re-open.
