### ISSUE TITLE
🐛[BUG][Quest] Waking Dreams Reward Choice

### ISSUE THREAD

**Issue by Polarthief** [HorizonFFXI/HorizonXI-Issues#1284]
**What does this bug affect?**
The reward choices for Waking Dreams (Diabolos Prime).

**Steps to Reproduce**
1.(?) Select the Pole and decline it. (unsure if this+step 2 triggered it or step 2)
2. Select any other equip reward and decline it.
3. The first option (Diabolos's Pole) will be replaced with the Earring, Torque, or Ring.

**Expected behavior**
The Pole doesn't get replaced with other options.

**Screenshots**
![image](https://user-images.githubusercontent.com/31106277/226485793-6d6963f2-2b5c-4b3f-ac05-0a491d4ef43b.png)

**Setup Information**
Game Version: v1.0
Horizon Launcher: v1.1.4

**Additional context**
None I can really think of. Choosing Gil or Pact with Diabolos did not replace the pole option, but the previous replacement was still there. I was NOT allowed to pick the Pole option after this happened (not that I wanted it anyway).

**Comment by HorizonPotato** [comment]
I would like to add to this bug report rather than file a new one.  

The Reward Choice option will still include a Pact with Diabolos even if you have Diabolos, and selecting this option will consume your Key item and reward you with nothing at all.  

I unfortunately fell victim to this because my first clear of Diabolos was more than a month ago so when I saw the option for a Pact with Diabolos I assumed I didn't have it as if i did, the option wouldn't exist, but turns out its bugged and RIP my time :|
