### ISSUE TITLE
🐛[BUG][Combat]Barrage gives incorrect mob TP

### ISSUE THREAD

**Issue by professorpalmer** [HorizonFFXI/HorizonXI-Issues#1302]
Barrage gives enough TP from a single hit to instantly cause a WS. You can have back to back WS used to instantly kill a shadow tank or even pull a mob with barrage that opens with a weaponskill. As early as 30 it's noticeable.

Very easy to recreate. Happens 100% of the time. Barrage = TP move, even if shots miss.

We have a lot of RNGs in the discord who have shared their similar experiences. I have screenshots included below of just a single example and the implications of the bug.

I pulled this mob with barrage/sharpshot. 4 hits landed. It instantly Meltdown'd.

![image](https://user-images.githubusercontent.com/24235924/227088845-dd59b276-5fd6-477e-9237-4754a557207c.png)

**Comment by lilisette** [comment]
I did some testing here just now myself, 53RNG/26 BST with 71 AGI against level 30 Diving Beetles in Carpenter's Landing, with the following results:

| Weapons | Bow/Xbow Delay | Arrow/Bolt Delay | Barrage Hits | Player TP gain | Mob TP Gain |
| --- | --- | --- | --- | --- | --- |
| Shortbow/Wooden Arrow | 360 | 120 | N/A (normal ranged attack) | 120 | 163 |
| Greatbow +1/Wooden Arrow | 524 | 120 | N/A (normal ranged attack) | 153 | 192 |
| Greatbow +1/Wooden Arrow | 524 | 120 | 4 | 612 | instant TP move from 90% health, presume 3k? |
| --- | --- | --- | --- | --- | --- |
| Republic Crossbow/Sleep Bolt | 272 | 288 | 5 | 734 | 3000 |
| Republic Crossbow/Sleep Bolt | 272 | 288 | 4 | 587 | 2936 |
| Republic Crossbow/Sleep Bolt | 272 | 288 | 3 | 438 | 1362 |
| Republic Crossbow/Sleep Bolt | 272 | 288 | 2 | 293 | 734 |
| Republic Crossbow/Sleep Bolt | 272 | 288 | 1 | 146| 183 |

Tested mob TP by immediately charming it after a freshly-spawned mob was hit with **only** the shots listed above and checking `/echo <pettp>` to ensure the only TP gain would be from the ranged attacks/barrages.

Based on this, I suspect that what's happening is that somehow the mob TP gain calculation is taking the *total* Base TP gained by the player (rather than the *per hit* Base TP gained by the player) and multiplying it by the number of Barrage shots landed? But Idunno where to find this in the ASB code yet
