### ISSUE TITLE
🐛[BUG][System/Combat] Summoning Magic Cast Time merit doesn't work.

### ISSUE THREAD

**Issue by catcatwaffleiron** [HorizonFFXI/HorizonXI-Issues#1462]
**What does this bug affect?**
_Summoning Magic Cast Time_ merit in Summoner cateogry.

**Steps to Reproduce**
Put 15 merit points into _Summoning Magic Cast Time_, then cast something. The casting time is exactly same as it was with 0 points in it. Should be 25% faster, which is a lot.

**Expected behavior**
It should make casting times faster.

**Additional context**
Fast Cast from RDM subjob has no effect on summoning cast times either, possibly related?

**Comment by Squinkerdoodle** [comment]
This merit should be "Elemental MP Cost" instead of what it's showing as now. Unfortunately merits haven't been able to be changed as of yet, though that is being worked on.

https://ffxiclopedia.fandom.com/wiki/Avatar_Perpetuation_Cost?so=search
"As of the March 27, 2012 Update the "[Elemental MP Cost](https://ffxiclopedia.fandom.com/wiki/Elemental_MP_Cost)" no longer exists; [Summoning Magic Cast Time](https://ffxiclopedia.fandom.com/wiki/Summoning_Magic_Cast_Time) has taken it's place and the Spirits overall Perpetuation Cost has been reduced."
