### ISSUE TITLE
🐛Purgonorgo Isle Clamming point not working[BUG][NPC?]

### ISSUE THREAD

**Issue by Khabraxis** [HorizonFFXI/HorizonXI-Issues#1470]
Purgonorgo Isle Clamming point @ (H-7)

This point no longer functions. I clam for hours on end and this point only ever says "It looks like someones been digging here". It has been like this for atleast the last 48 hours. 

**Steps to Reproduce**
Simple attempt to clam with clamming bucket at this point. 

**Expected behavior**
It will only respond with "It looks like someones been digging here".

**Screenshots**
Will not prove anything. someones gotta come try it.

**Comment by Kyne09** [comment]
Expected behavior
You should be able to interact with this point and get the "dig" dialogue box every 10-15 seconds.  Currently it gives the cooldown dialogue indefinitely.

Screenshots
![image](https://user-images.githubusercontent.com/113271225/233744637-040e7d6a-c448-436f-b2f1-bc2d125c7682.png)

**Comment by Kyne09** [comment]
After discussing with Wintersolatice the root cause is that the in-use status of the node is tied to a server variable.  If a player disconnects while accessing the node the server variable gets stuck.  This variable persists through maintenence as well.  It can be fixed by anyone with !exec priveleges.

!exec SetServerVariable("ClammingPoint_" .. target:getID() .. "_InUse", 0)` should fix it if someone with priveleges targets the broken node

**Comment by Khabraxis** [comment]
(I-9) North side clamming point no longer functions.

**Comment by clanofartisans** [comment]
This was fixed on June 9 thanks to Wintersolstice.
