### ISSUE TITLE
🐛[BUG][System/Combat] Harajnite / Cyclopean Conch fishing issue.

### ISSUE THREAD

**Issue by ReeseWatanabe** [HorizonFFXI/HorizonXI-Issues#1501]
**What does this bug affect?**
The NMs Harajnite and Cyclopean Conch can become unable to be fished up (via unable to get a bite) until map/server reset if their prompt is failed or the boat docks before the monster is fished up.

**Steps to Reproduce**
Attempt to fish up Harajnite and/or Cyclopean Conch. Fail the fishing prompt and/or do not reel them in as the boat docking automatically cancels the fishing prompt.

**Expected behavior**
Harajnite and Cyclopean Conch should always be able to bite the rod and be fished up so long as one of them is not currently alive.

**Additional context**
This was an issue on WingsXI regarding the Devil Manta where if someone failed the prompt, Devil Manta could not be fished up again until map/server reset.

It's possible my context is wrong and this explanation isn't exactly to how the issue operates, it could be that they become exponentially harder to get a bite from to the point of seeming non-existent should the prompt be failed. Could be that when he's despawned in some way he no longer bites, etc.

The NM Harajnite drops a material for a best in slot Black Mage piece of gear.

**Comment by xperian** [comment]
I think this happens with all the monsters that can be fished up on that specific boat ride, up to the point where no monster can be fished up. I managed to fish up Cyclopean Conch once, but in the process I had a substantial of line breaks, this continued to the point where no monster could be fished up.

**Comment by Tiby92** [comment]
I believe this only happens when someone is trying to fish a monster up while the boat zones. 
Failing to fish this up (line break) did not seem to make this vanish from the pool. But definitely, one by one, the monsters vanish. When farming this and keeping the Harajnite out during zones (to be able to kill on next ride due to time limitations) it was possible to keep it not getting bugged for some time. Once this procedure stopped it quickly got bugged.
