### ISSUE TITLE
Drop Rate on NM Count Bifrons 

### ISSUE THREAD

**Issue by papojp24** [HorizonFFXI/HorizonXI-Issues#1588]
Questioning the drop rate of Absorb-DEX scroll from NM in Castle Zvahl Keep (Count Bifrons). I'm 0/20 with TH3 and I don't know if there is a bug or if the devs significantly decreased the drop rate relative to retail.

**Comment by TracentEden** [comment]
The drop rate has a base rate without TH of 5% and with TH3 a rate of 7.5%. This is comparable to the base rate without TH from [ffxidb](http://www.ffxidb.com/zones/162/count-bifrons). Note the TH3+ rates on ffxidb are not reliable because they include drops from retail with up to TH14. Thanks for reporting!
