### ISSUE TITLE
🐛[BUG][System] Pirate's Gun Recipe not available 

### ISSUE THREAD

**Issue by AnonymousMithra** [HorizonFFXI/HorizonXI-Issues#1680]
**What does this bug affect?**
Pirates Gun can not currently be crafted, as it is a material for Stage 3 of the Relic Gun quest this makes any progress past this point impossible.
**Steps to Reproduce**
Have Required Smithing and Bonecraft levels
Start Synth with Fire Crystal
Place Steel Ingot, Darksteel Ingot and Turtle Shell into slots
Fail to Craft

**Expected behavior**
Gun is made

**Additional context**
I can understand that being a almost worthless piece of gear most people didn't even know how to craft in Era with little history available that this item keeps being overlooked, but as a literal requirement to build a Relic in this Era i think it very much does need to exist. As my understanding it was fixed once before and was either temporary or reverted as it has not been craft-able for 4~ weeks since I've been trying at least.

**Comment by siknoz** [comment]
This existed in 2004 as someone was able to turn in for the relic, doesn't make sense to have added an item needed for relic during TOAU era. The reason you can't synth is because it's marked for TOAU era, just needs to be changed to ROZ.

![image](https://github.com/HorizonFFXI/HorizonXI-Issues/assets/78240569/ceec4563-00a8-4960-be95-104ac7017f2b)

**Comment by TracentEden** [comment]
This will be fixed by this PR https://github.com/AirSkyBoat/AirSkyBoat/pull/3234
