### ISSUE TITLE
🐛[BUG][NPC] Wyvern moving while slept bug.

### ISSUE THREAD

**Issue by Birdy-gif** [HorizonFFXI/HorizonXI-Issues#169]
**What does this bug affect?**

Pet wyverns follow their masters while slept if not engaged at time of sleep.
**Steps to Reproduce**

**Expected behavior**

Shouldnt move while slept at all.
**Screenshots**

**Setup Information**

**Additional context**

**Comment by luke-belinc** [comment]
So I am a still new so bare with me, but I think this can be fixed by adding 2 listeners to `scripts\globals\wyvren.lua` to call `pet:removeFollower` or `pet:addFollower` based on whether the gained effect is flagged as `PREVENT_ACTION` . 

Example:

```lua
entity.onMobSpawn = function(mob)
  local master = pet:getMaster()
  ...

  mob:addListener("EFFECT_GAIN", "PET_WYVREN_EFFECT_GAIN", function(pet)
    if pet:hasStatusEffectByFlag(xi.effectFlag.PREVENT_ACTION) then
      pet:removeFollower(master, pet)
    end
  end)
  
  mob:addListener("EFFECT_LOSE", "PET_WYVREN_EFFECT_LOSE", function(pet)
    if not pet:hasStatusEffectByFlag(xi.effectFlag.PREVENT_ACTION) then
      pet:addFollower(master, pet)
    end
  end)

  ...

end
```

Like I said, I am new, so I am not exactly sure which steps to take to test this but if someone wants to help me with that I would be forever grateful. Moreover, I am not sure if this an issue that persists for more than just wyvrens and if so it might be a better solution to go up a level and do this for each pet that gains a status effect flagged as `PREVENT_ACTION`. But it seems like Wyvrens are treated differently than other pets(?) so it made sense to just start there.

**Comment by luke-belinc** [comment]
So I found a solution, assuming this behavior is expected for all slept pets. There are a couple ways this could probably be implemented but essentially checking to see if the pat can follow a path using `CAIContainer::CanFollowPath` inside of `CPetController::DoRoamTick` is useful for checking to see if the pet can move at all. 

That said, I added the following code to `pet_controller.cpp:74`

```CPP
// if pet can't follow then don't
if (!PPet->PAI->CanFollowPath())
{
    return;
}
```

**Comment by luke-belinc** [comment]
This can be closed: https://github.com/AirSkyBoat/AirSkyBoat/pull/493

**Comment by The-Aerec** [comment]
Closed in above mr (needs to be ported to HXI)
