### ISSUE TITLE
[BUG] [QUEST] Reap What You Sow still currently not completable

### ISSUE THREAD

**Issue by Rowboyz** [HorizonFFXI/HorizonXI-Issues#1700]
[BUG] [QUEST] Reap What You Sow still currently not completable 
**What does this bug affect?**
Repeatable "Quest Reap What You Sow" can not be completed by either Sobbing Fungus or Deathball trade and results in no actions being taken by the NPC. 

**Steps to Reproduce**
Talk to Mashuu-Ajuu ontop of the school in Windurst Waters.
Unless conflicting with another quest, Let Sleeping Dogs Lie, it should flag Reap What You Sow.
Currently does neither. Trading the items to him, having already previously completed the quest before, results in nothing.

**Expected behavior**
Trading a Sobbing Fungus results in afew lines of text then a reward of 500. Stationary Set was previously removed from the rewards.
Trading a Deathball results in afew lines of text then a reward of 700. Stationary Set was previously removed from the rewards.

**Setup Information**
Standard setup and near vanilla addons. 

**Additional context**
Issue has be closed back in May stating it should have been fixed and to keep notice on the patch notes. After reviewing the patch notes from then till now, issue has not been resolved and still persists.

**Comment by PublicXI** [comment]
I just tested this and can confirm that it is fixed. Unfortunately, because you completed the quest before the fix was introduced, you'll need a GM to help you. They can simply delete the quest from your character, or they can set the quest status to QUEST_ACCEPTED. Please show this to a GM and they should be able to help. Sorry for the inconvenience.

The quest information is available [here](https://github.com/AirSkyBoat/AirSkyBoat/blob/staging/scripts/quests/windurst/Reap_What_You_Sow.lua#L4) for any GMs that need it.
