### ISSUE TITLE
🐛[BUG] BCNM - Royal Jelly

### ISSUE THREAD

**Issue by Squinkerdoodle** [HorizonFFXI/HorizonXI-Issues#195]
**What does this bug affect?**
BCNM is dropping a Shikargar which is a lvl 99 sword (possibly instead of the Shikar Bow? Received the Shikargar twice but did not get the bow over multiple runs)

Additionally just wanted to confirm that the Queen Jelly's HP is based off the total HP of the merged Princess Jellies, instead of just a flat amount per # of Princesses that merge in the center. (I.E. 2 princess jellies with full 600 HP and a third with 7 HP would = a spawned Queen Jelly with 1207 / 1380(max) HP)

**Expected behavior**
BCNM reward should include the Shikar Bow instead of the Shikargar.

**Screenshots**
![image](https://user-images.githubusercontent.com/112344508/195171136-414fa2d9-d500-4d97-a633-df6fd30e59a3.png)

**Setup Information**
Version 30220906_0

**Comment by dallano** [comment]
haha so glad your're catching these.

**Comment by dallano** [comment]
I'll double check on the HP behavior soon

**Comment by dallano** [comment]
@Squinkerdoodle What I fixed with queen's HP is I set her max possible HP to its highest capability. Beforehand her HP was being calculated to that of a regular lvl 45 mob. So now her HP should be capable of receiving 8 full HP jelly mobs. It will also reflect HP accordingly if she was spawned from only 1 mob.
