### ISSUE TITLE
🐛[BUG][Combat] Byakko Roar tp move is wrong

### ISSUE THREAD

**Issue by ccl085** [HorizonFFXI/HorizonXI-Issues#312]
**What does this bug affect?**

Byakko's Roar tp move hit for 0 dmg
**Steps to Reproduce**

1. pop byakko
2. !tp 3000 till it use roar
3. observe chat log "Byakko use Roar -> XXX take 0 damage"
**Expected behavior**

Roar should not do damage and be an aoe paralyze tp move

**Screenshots**

![Ccldd_2022 10 27_154811](https://user-images.githubusercontent.com/48790940/198303032-206cecac-9c54-41fa-80c8-b68847c1bab2.png)

**Setup Information**

**Additional context**

**Comment by Squinkerdoodle** [comment]
This issue is not only limited to Byakko.
![image](https://user-images.githubusercontent.com/112344508/198700635-c2e50cd7-1721-4ca3-afcf-9ea0a839e181.png)
![image](https://user-images.githubusercontent.com/112344508/198700662-6165a84c-f97e-4375-b7df-2243ea3b12c4.png)
![image](https://user-images.githubusercontent.com/112344508/198701123-d3a59c95-e0aa-484b-a211-d2a35fa580ce.png)
![image](https://user-images.githubusercontent.com/112344508/198701410-183ddc76-92c3-4556-bc04-ad42ddc780b6.png)
![image](https://user-images.githubusercontent.com/112344508/198701451-8c89d5ec-27cd-42ee-aeea-d2ea40a47d07.png)
![image](https://user-images.githubusercontent.com/112344508/198701549-98e075ea-e5ae-4aed-916d-ae666075c21d.png)

**Comment by CriticalXI** [comment]
I believe this should already be fixed with the problem we encountered with mob tp enfeeble moves being broken last week. Please feel free to re-open if this is still happening.
