### ISSUE TITLE
🐛[BUG][NPC/Enemy Name] Maze of Shakhrami Incorrect Mob Names

### ISSUE THREAD

**Issue by alessa89** [HorizonFFXI/HorizonXI-Issues#431]
**What does this bug affect?**
found a number of mobs in shakrami all with the name "Crypterpillar" which should be just crawlers, found some slimes, leeches, scorpions, bats with this name  

**Steps to Reproduce**
seen on shakhrami map 1 around I-7

**Screenshots**
![image](https://user-images.githubusercontent.com/115948656/203391229-cbea9424-4d26-46fc-8d26-fc6dd0e63454.png)

![image](https://user-images.githubusercontent.com/115948656/203391273-2a0470bf-1b13-429f-bb2d-d72e6f224ad1.png)

**Comment by alessa89** [comment]
some skellies and leeches are also having an identity crisis as chaser bats around I6
![image](https://user-images.githubusercontent.com/115948656/203393744-e67503fc-6b12-45e2-8b61-d4f28da8b99f.png)

**Comment by Squinkerdoodle** [comment]
Do you have the mob renamer installed / active?

**Comment by Squinkerdoodle** [comment]
I'm not seeing any issue with the mobs like this. I do have the renamer installed / active though. @alessa89 This ticket can be closed due to it not being an issue on Horizon since the renamer will be included.

![image](https://user-images.githubusercontent.com/112344508/205515234-f7485432-b330-4596-ba49-683a7c8b35c5.png)
![image](https://user-images.githubusercontent.com/112344508/205515334-01d1af82-1f55-4b87-9c6f-bb299bb3ab7c.png)
