### ISSUE TITLE
🐛[BUG] Northeren Temenos

### ISSUE THREAD

**Issue by Birdy-gif** [HorizonFFXI/HorizonXI-Issues#442]
**What does this bug affect?**

The HP MP chests never spawned. We were able to open all of the chests when we should only be allowed to chose one. Astral flows is hitting for 1.8k+ damage. Final chest didn't drop anything and didn't kick us out.
**Steps to Reproduce**

**Expected behavior**

**Screenshots**

**Setup Information**

**Additional context**

**Comment by Twispn8** [comment]
Floor 1 : Killed all mobs and only 2 chests spawned and was able to open both. Should spawn all 3 chests and only open one. 

Floor 2 : only 2 chests spawned. [Skadi]
 Will charm whomever has the most hate as her 2hr ability. ( Skadi's current 2hr ability is familiar.) Beli's EES was very weak. 182pts of damage not sure if intentional or not.

Floor 3 :  Telchines Dragoon did a 2hr ability animation but no chat log text of what was used. and same issue w/ chests.

Floor 4 : all demons seem to have correct 2hr's..smn 2hr was 1404 only 2 chests again able to open both

Floor 5 : all ants used correct 2hr..rng 2hr very underwhelming w/ 69 pts of damage only 2 chests again able to open both

Floor 6 : all tonberry used correct 2hr. searing light x2 was 1351 each 2hr Ifrit's inferno was 1351 as well. only 2 chests again able to open both

Floor 7 : all goblins used correct 2hr's but they did not drop 1-2 coins no items from last chest and did not kick out of limbus.
did not see any coin drops from the regular mobs on the floors went off information on this wiki https://ffxiclopedia.fandom.com/wiki/Temenos_-_Northern_Tower?oldid=59764  / Revision as of 00:54, 11 April 2006

**Comment by Squinkerdoodle** [comment]
@jmcmorris
