### ISSUE TITLE
🐛[BUG][Combat] DRG Wyvern's are very rarely using elemental breaths other than fire

### ISSUE THREAD

**Issue by montijin** [HorizonFFXI/HorizonXI-Issues#444]
**What does this bug affect?**

Dragoon Wyvern's Elemental breaths

**Steps to Reproduce**

Go on the test server and weaponskill a lot on DRG. Notice the disparity between Flame Breath compared to all other breaths. 

**Expected behavior**

The breath attack used by the wyvern is random, but usually favors the SDT weakness of the mob.

**Screenshots**
![image](https://user-images.githubusercontent.com/2160211/204188855-34753d1b-5fc7-4018-b28f-441c7aab55af.png)

**Setup Information**

11/27/2022 test server 

**Additional context**

https://ffxiclopedia.fandom.com/wiki/Elemental_Breath

**Comment by Kyne09** [comment]
Confirmed, used 50 weaponskills and got 50 Flame Breaths, nothing else.  Could be tied to last update.

**Comment by Kyne09** [comment]
Circling back to testing on Wyvern Breath only using Flame Breath, I'm running around Sky and fighting elementals and against the Elementals it's only using what they're weak to if the Wyvern is capable of casting it.  

So for example Air Elemental, you always get the Wyvern using Frost Breath.  Ice Elemental, Fire Breath, Earth Elemental Gust Breath etc.  Dark and Light it just uses Fire since it doesn't have anything to hit weakness

However if you fight any non-elemental mob it only uses Fire Breath.  Doesn't matter what it's weak to.

**Comment by StyrkaGG** [comment]
this is currently still an issue i have not got any thing but fire breath

**Comment by dallano** [comment]
it seems what's happening is when mobs don't have any weaknesses, it defaults to flame breath.
