### ISSUE TITLE
🐛[BUG] Jailer of Love Issues

### ISSUE THREAD

**Issue by Birdy-gif** [HorizonFFXI/HorizonXI-Issues#460]
**What does this bug affect?**

- Adds lose agro and don't reaggro after everyone uncharms. 
- JoL doesn't summon sharks after it summoned the rest of its pool of adds.
-  JoL was healing from our blunt, piercing damage, and any magic damage JoL became resistant to at some point. 
  Not sure what caused us to heal with physical damage.
**Steps to Reproduce**

**Expected behavior**

**Screenshots**

**Setup Information**

**Additional context**

**Comment by Squinkerdoodle** [comment]
Just watched a LS attempt this today (3/19) on the live server. The above issues are still present.
~JoL does not continue to summon phaubo(sharks) after the summon pool is exhausted and it's auto-regen is down. It will do the summoning animation, but nothing will actually be summoned.

~JoL heals from physical damage types (slashing / piercing / blunt) and will cycle through what it absorbs. This is opposite of retail where it would absorb a random elemental magic type (which would change every 2 minutes?)

~JoL's model is smaller than it should be. Currently it uses a normal yovra model instead of a larger sized yovra model.

~JoL was flying up into the air periodically instead of only staying on the ground.

~JoL seemed to run out of mp and stopped casting spells?
