### ISSUE TITLE
🐛[BUG][Mission] - Darkness Named

### ISSUE THREAD

**Issue by Squinkerdoodle** [HorizonFFXI/HorizonXI-Issues#47]
**What does this bug affect?**
Diabolos fight during the CoP mission Darkness Named

**Steps to Reproduce**
Start the fight with Diabolos and repeatedly give it 3000 TP / watch for spells cast.

**Expected behavior**
Tiles should drop periodically throughout the fight. Diabolos should also use Camisado and Ultimate Nightmare in addition to Noctoshield / Nightmare.

**Screenshots**
https://drive.google.com/file/d/1WYPgmcdUrYjmp4eFNzcuR7A3hnkHX767/view

**Setup Information**
Version 30220802_3

**Additional context**
Did not use godmode, only immortal. Landed silence / slow / paralyze as 40 whm / 20 blm, not sure what's supposed to land on him or not. Used Ruinous Omen (2hr) @ 50% HP, not sure if he uses that in this fight as it's not on the wiki. No tiles dropped at all during the fight. Casted all appropriate dark magic spells. The only TP moves it used were Nightmare and Noctoshield, did not use Camisado or Ultimate Nightmare (tested by giving it 3000 tp roughly ~100 times.

**Comment by paladindamarus** [comment]
This appears to have been (mostly) fixed by a previous commit.  Diabolos uses all correct BPs, tiles drop, etc.  Only thing to change is to remove RO from this fight.  Resistances are an issue on a few other things, but some testing would need to be done to confirm what should and shouldn't land.

Submitting separate update via ASB to fix RO usage.

**Comment by paladindamarus** [comment]
Solved through ASB update: https://github.com/AirSkyBoat/AirSkyBoat/pull/383
