### ISSUE TITLE
🐛[BUG] Further Garrison Issues

### ISSUE THREAD

**Issue by Squinkerdoodle** [HorizonFFXI/HorizonXI-Issues#487]
**What does this bug affect?**
Drop rate off of mobs might be too high. For mannequin parts it seems the legs and feet are in different pools, making multiple drops from 1 mob possible. The mannequin parts may need to be a single loot pool.

Waves not scaling properly with # of parties involved.

https://www.youtube.com/watch?v=aq4NeU1GuJY & https://www.youtube.com/watch?v=_NXN3bykkMY - shows that Level restriction buff should not wear until talking to the outpost guard after clearing the final wave, which also gives gil and rewards. As is on the test server the garrison completes after killing the final mob / wave, and possible loot rewards go into the party loot pool with no chat entry. Additionally there is no gil reward for completion.

Shouldn't earn any xp or get any crystal drops from enemies. As is, xp is randomly gained from defeated monsters (not sure of reason / pattern for it).

Dying during the garrison and being raised does not remove the level restriction buff.

West Sarutabaruta garrison NPCs had no battle animation.

West Ronfaure garrison NPCs were level 30-35.

NPC levels need to be checked on garrisons, some NPCs spawning higher than they should be possibly. Pashow garrison had multiple level 35 NPCs spawn. Max level of the mobs in this garrison was also 35, with the lowest reaching 30. With NPCs reaching level 35 the garrison seemed easier than intended, with NPCs able to solo mobs on their own.

Also need to re-open the question of a single player being able to start garrisons in multiple zones per conquest tally. Some testers stated this should be the case, instead of just once total (regardless of zone) per tally week.

**Screenshots**
![image](https://user-images.githubusercontent.com/112344508/206826895-8ef2c49b-c5d4-4e8c-9d4a-2aee9a8ff633.png)

**Setup Information**
Version 30221103_1

**Comment by Squinkerdoodle** [comment]
@xkoredev sorry for more issues

**Comment by xkoredev** [comment]
Finding issues is good. no need to be sorry :)

* Mannequin Drop rates

No idea what the loot table was based off of tbh. Do we have any data on percentages?

* Waves not scaling with # of parties

We had no captures whatsoever of more than 1 party, but this video https://www.youtube.com/watch?v=GIIQdgCKdnY shows 4 mobs and not 6 on round 1 with 3 parties. One limitation we do have, and I think retail does too, is 8 mobs max at once (given their ids from captures). We can work around it, but I think I am fine with limiting to 8 max for simplicity.

* Completing event via npc

This seems like lower priority and I'm personally okay just leaving it as is. 

* XP / crystals gained

Will look into it

* "Additionally there is no gil reward for completion."

Do you mean there is and there shouldn't be? Or there isn't and there should be?

* Losing Level Cap buff on death

This is actually incorrect in the wiki. The level cap effect stays on death / raise, as seen on this capture:
https://youtu.be/TsPHl-NP2Zg?t=1651

* Battle animations

This is due to how we added the non captured npc models. I will do a second pass and make sure all zones work as intended

* NPC Levels

The npcs themselves also have the level cap status as far as I know, so this shouldn't happen. I will check

* Starting once per tally per zone

If wiki says it can be done, since we have no captures saying otherwise, I'm fine changing it.

**Comment by Squinkerdoodle** [comment]
"Additionally there is no gil reward for completion."
Do you mean there is and there shouldn't be? Or there isn't and there should be?

Currently there isn't, and there should be based off captures.

**Comment by Squinkerdoodle** [comment]
The captures of the lvl 20 one was giving 2k gil, not sure of higher level ones.

**Comment by xkoredev** [comment]
Okay some info on wave videos I was able to find:
https://www.youtube.com/watch?v=_NXN3bykkMY

This shows 2 parties, with the following spawn schedule:
Wave 1:
4
2
Wave 3:
4
2
2
Wave 4:
4
2
2
Boss

**Comment by xkoredev** [comment]
The only videos I can find on 18 people both show only 3 waves. I don't get it. But both match... so I think this is the right schedule:

Wave 1:
4
2
Wave 2
6
2
Wave 3: https://youtu.be/dUQS26W67I4
4
2
2
Boss

**Comment by xkoredev** [comment]
RE: Mob levels.
Database is set for mob levels that go from level cap to level cap +5 for a given garrison.
I think that makes sense since EM mobs would be too easy for alliance content.

**Comment by xkoredev** [comment]
Prior order to have it written down here:
Waves > NPC Levels > Drop Rates > XP / Crystals > Gil Reward > Battle Animations

**Comment by xkoredev** [comment]
https://github.com/AirSkyBoat/AirSkyBoat/pull/2215
Fixes NPC Levels > Drop Rates

**Comment by xkoredev** [comment]
https://github.com/AirSkyBoat/AirSkyBoat/pull/2216
Adds gil payout

**Comment by xkoredev** [comment]
I'm going to defer XP / Crystal rewards as I think they are minor side effects considering how annoying it would be to fix. Right now we check for battlefield status only to avoid granting exp :/
