### ISSUE TITLE
🐛[BUG][Combat] Summoner Magic Burst bug with Bloodpact: Rage

### ISSUE THREAD

**Issue by XIBrixy** [HorizonFFXI/HorizonXI-Issues#679]
**What does this bug affect?**

Summoner's Magic Burst with Bloodpact: Rage
**Steps to Reproduce**

Magic burst with a Bloodpact: Rage
**Expected behavior**

Damage should increase on a magic burst compared to normal damage. It is currently going way down instead.
**Screenshots**

https://imgur.com/a/3H8NxTO
**Setup Information**

**Additional context**

The game appears to be using a different formula to calculate Bloodpact burst damage compared to regular magic burst damage, or not added to the formula at all?

**Comment by Minasojo** [comment]
I have some additional screenshots replicating this same issue, but also discovering a new second issue related to the same function.

Whenever a Tier IV Magic is used (ex: Aero IV, Water IV, etc...) the text entry in the log that reports the result of the MB effect as whatever spell was cast voided out, appearing as simply "Shiva uses ." instead of "Shiva uses Blizzard IV" 

Screenshots provided illustrating this from reproductions found here: https://drive.google.com/drive/folders/174Do-_LWRkIyd_sm-lTs-NQv_ijtuf8F?usp=share_link

**Comment by CriticalXI** [comment]
Should be working as of a recent patch, fixed by Frank and Shozokui.
