### ISSUE TITLE
🐛[BUG][Combat] PCs do not currently get TP when hit by magical attacks

### ISSUE THREAD

**Issue by rujind** [HorizonFFXI/HorizonXI-Issues#680]
We do not currently get any TP when we are hit by magical attacks. 
https://ffxiclopedia.fandom.com/wiki/Tactical_Points?so=search
"TP is also gained any time you take damage from a melee or magical attack. Damage Over Time spells, such as Dia and Poison, will only give TP if the initial cast does direct damage, not for the damage dealt by the status effect."

**Comment by CriticalXI** [comment]
Need a capture or more details on how much TP players should receive.

**Comment by siknoz** [comment]
In-era : https://youtu.be/IJM_dUb9UqA?t=205 - RDM gets hit with Fire3 (breaks stoneskin) gains 5 TP (=50 TP on horizon)
https://youtu.be/IJM_dUb9UqA?t=291 - Bliz2 hits and gaints 5 TP (=50 TP on horizon)
https://youtu.be/0NJm2hkStEw?t=191 same, 5 TP
https://youtu.be/p-P-VwEihEM?t=224 Maat uses Holy, gives 5 TP
https://youtu.be/8NzoD6SdE9A?t=159 Ouryu Stonega3 gives 5 TP. 

So that's WHM elemental (holy) BLM single target(fire3, bliz2, bliz3), BLM -ga3 (Stonega3) all giving 5 TP each, I think it's ok to assume that magic hitting should add 50 TP on horizon per hit.
