### ISSUE TITLE
Yara Ma Yha Who Not spawning correctly.🐛[BUG][NPC/Combat/]

### ISSUE THREAD

**Issue by Kagekiki** [HorizonFFXI/HorizonXI-Issues#795]
**What does this bug affect?**
Yara Ma Yha Who spawn may be inaccurate. Based on retail (Yes I know we are era+) you are to trade a water every 50 mins to the ???. after 3-4 tries it will spawn the little gremlin. Currently been here 4 hours and only been able to trade it 2 waters so far and it has back tracked on what it says from sprout is getting better to looking withered. I have seen on other Pivate servers there is an issue with the code that if you try and trade a water too early instead of just telling you you cant give it more water. It also resets the timmer to trading it water back tracking your progress on the trade ins as it sits too long. 

**Steps to Reproduce**
 Trade water to the ??? then after 30 mins try and trade it a water then after an hour from first trade try and trade it again. 

**Expected behavior**
  you should be able to trade every 50 mins instead of it resetting timer 

**Screenshots**

**Setup Information**

**Additional context**
(https://ffxiclopedia.fandom.com/wiki/Yara_Ma_Yha_Who?oldid=134842)

**Comment by Kagekiki** [comment]
Ok so got it to spawn after 3 turn ins but the timing on turn ins is a little borked it seems first turn in was 11:49 am PST 3rd trade is was 3:35 pm PST

**Comment by panicstevenson** [comment]
I took a preliminary look at this (didn't sit down to test it fully), but it looks like it only resets the timer is the trade was valid.
There's 3 conditions for the trade to be valid:
- Traded a Distilled Water
- Yara Ma Yha Who isn't spawned
- It's been 50 minutes since the last trade
It doesn't look like that timer is set outside of that condition, but again I didn't sit down to test fully here.
