### ISSUE TITLE
[BUG][MONSTER/NM][COMBAT] Aura Pots - Spectral Barrier blocking slashing physical weaponskills

### ISSUE THREAD

**Issue by YarAsti** [HorizonFFXI/HorizonXI-Issues#870]
Spectral Barrier is supposed to just be a magic shield however when the Aura Pots in Sky used it our weapon skills were returning 0 damage however basic attacks were still doing damage.

Spectral Barrier (https://gyazo.com/43e0deedb78761ebefbe017ec3e56d0c)

Image showing 0 damage returns on Gekko, Armour break, & Swift Blade (https://gyazo.com/b4cc35e69b1192d57dcf3330f477d786)

**Comment by ThrisStraizo** [comment]
To add onto this, it seems to be specifically slashing weaponskills that magic immunity is blocking.  In ENM 50 Pulling the Strings, after killing the Physical immune orb, you can start hitting the main orb.  However, slashing weaponskills still do 0 damage to it likely because it's still magic immune.  I'm essentially locked out from being able to solo it on my warrior :(

**Comment by CriticalXI** [comment]
Fixed in a recent patch
