### ISSUE TITLE
🐛[BUG][Ropunono /Heaven Cent/ Trap room/ No Key Item]

### ISSUE THREAD

**Issue by Cwope** [HorizonFFXI/HorizonXI-Issues#882]
**What does this bug affect?**
I'm trying to complete this quest for 4,800g, but it has cost me two !unstuck as it does not work. You have to search chests for the "proper coin" but when you find the proper coin, you cannot pick it up. The chests are only allowing you to pick up the incorrect coin - and then you're still trapped in a room waiting for a GM to come and get you.

**Steps to Reproduce**
Trade Rusty Key to Iron Door in Maze of Shahkrami - try and compelte quest "Heaven Cent" and leave the room.

**Expected behavior**
You are trapped in a room, and the correct quest item will not be rewarded if you choose to pickup the "proper" coin

Please let me have my 4,800g T.T

**Comment by Jibblesenbits** [comment]
I have done the same quest, and run into the same problem. I could not pick up any coin and ended up doing !unstuck to get out of the room because it would not let you exit. - Jibbles

**Comment by chriskostelec** [comment]
Can confirm as well, same issue.

**Comment by chriskostelec** [comment]
Update: Still broken after trying due to patch notes. However now the Rusty Key is used but the correct shilling choice never showed up. Also I was unable to even grab an incorrect shilling piece now. I tried going back to the NPC (their dialog is correct, just asked me to get the shilling piece), got another Rusty Key, same issue. I'm not sure if possibly some of us are in a state of corrupted limbo or if no one can do it now either.

**Comment by Ziggomatica** [comment]
I'm in the same state as chriskostelec.  Can't pick up the correct shilling piece or even the incorrect one no matter what option I choose when examining the chests.

**Comment by dallano** [comment]
Thank you for the reports everyone. I will look at this asap

**Comment by dallano** [comment]
Fix has been made and will be incoming asap!

**Comment by Clonegoat** [comment]
Just wanted to confirm this issue is not yet fixed, I ran into the same issue as the people above, currently in the room and cannot claim the correct coins

**Comment by Clonegoat** [comment]
Also I'm noticing that I'm now "locked out" of the option occasionally to even look at a coin, so I think the game things I've already taken the "proper ones" I've been presented, which may result in being locked out of the quest completely? Unless it resets, somehow.

**Comment by dallano** [comment]
Are you testing on live horizon? Or did you build the above PR directly and test locally? Because I don't believe it's even in beta yet

**Comment by Clonegoat** [comment]
This was just live horizon last night, right before my post. ver 30221103_1
Was just updating since I saw only this closed post, marked as completed, instead of opening a new one

**Comment by dallano** [comment]
Should make its way into live horizon. Please check the patch notes for when it reaches it

**Comment by AmorPlatonicus** [comment]
I just had the issue where when I choose to take the correct shelling piece, it doesn’t give me the item.
I opened a GM ticket on the horizon discord and submitted a few videos of the quest not working. The GM instructed me to go see what Ropunono says when I return to her since from their end, everything looked correct.
If I choose an incorrect shelling piece, it gives me the item, but when I take it back to Ropunono, she tells me it’s a fake.
I went back to the maze, got another rusty key, went into the room, and the same issue happened again but this time I took video of it not working with my phone. I submitted it in the GM ticket and the GM instructed me to come here, create an account, and submit a bug report.
This bug is not fixed. When will it be pushed live?

**Comment by dallano** [comment]
Thank you for all of your effort and hard work into looking into this bug. I will reexamine this issue and get a fix for it ASAP

**Comment by dallano** [comment]
Is there a chance that your inventory was full? @AmorPlatonicus

**Comment by dallano** [comment]
Unfortunately I'm unable to replicate the issue you're experiencing.. hmm..

**Comment by AmorPlatonicus** [comment]
> Is there a chance that your inventory was full? @AmorPlatonicus

No. If you are able to view the video I uploaded to YouTube, you will see my inventory was 3/60.
