### ISSUE TITLE
🐛[BUG][Quest]  "It's Raining Mannequins" -- Does not issue the mannequin!!!

### ISSUE THREAD

**Issue by kevinstaresdarbon** [HorizonFFXI/HorizonXI-Issues#902]
**What does this bug affect?** --> After Gathering the 5 Mannequin Parts and completing the quest "It's Raining Mannequins" the npc never moves onto the finalstep of issuing the mannequin.

I have handed in the 5 parts of the mannequin to Fyi Chowlmoh and she moved onto the wait step with text that starts "I'll get to work right away on the joints...", however, after waiting for over 4 earth hours for her to issue the mannequin she still just repeats the same text.   ffxiclopedia says 1 game day is a long enough wait.   I have zoned, relogged and done some of the NIN q before returning. still the same text.
**Steps to Reproduce**

gather 5 mannequin parts, walkthrough q "Its raining Mannequins": Fyi Chowlmoh --> Selbina ---> North San d'oria ---> Fyi Chowlmoh ---> trade the 5 pieces ---> commence waiting --->  ........
**Expected behavior**

She should move past the waiting step and issue me with a mannequin of my current race and gender and give me options to buy more.
**Screenshots**

![img_20230122_023352](https://user-images.githubusercontent.com/5858232/213897989-10332cbf-cc51-4cf5-af9b-fb586aed3c75.jpg)

**Setup Information**

version 1.1.4
**Additional context**

![img_20230122_023352](https://user-images.githubusercontent.com/5858232/213898037-e396cd17-0a7d-4d89-8248-6045b65e052f.jpg)

**Comment by paladindamarus** [comment]
@kevinstaresdarbon Out of curiosity, have you gone back already to see if she gives you the mannequin?  There is a time period that has to pass before she will give it to you.  Just want to make sure that's not part of the issue.

**Comment by kevinstaresdarbon** [comment]
Yes, I have returned at many  points, and again just now. Still the same text

**Comment by paladindamarus** [comment]
Ok,  interesting.  I just checked your live variables and they are set correctly.  Let me dig in a bit further

**Comment by kevinstaresdarbon** [comment]
Just relogged and tried again, same result. awesome ty

**Comment by paladindamarus** [comment]
Alright, I have to get a testing command loaded onto the live server, which needs one of the staff to do.  I'll finish this up tomorrow, but I think it's one of two problems.  Should have something this weekend though.

**Comment by paladindamarus** [comment]
Correction -- Think the culprit might be that the code is waiting for JP Midnight, which is not the intended wait time.  You should be able to receive the mannequin in about 5 hours which would be before I can get a fix in.  If you still don't get the item, let me know because that means we have TWO issues to resolve...

**Comment by kevinstaresdarbon** [comment]
will do

**Comment by kevinstaresdarbon** [comment]
seems to be a jpm timer. i got the cs and mannequin just now

**Comment by paladindamarus** [comment]
> seems to be a jpm timer. i got the cs and mannequin just now

Perfect, I was just about to ask that.  I had to look up a couple of different wikis, but it does appear that "JP Midnight" actually is correct according to some.  I talked to the staff, and since this is still functioning but not game-breaking, we'll leave it as-is and make sure the GMs and stuff know that this is the case.  I'll close the ticket.  Thanks!
